#!/bin/bash

echo "🎯 Quick Deployment Checklist"
echo "=============================="
echo ""
echo "Before deploying, make sure:"
echo ""
echo "✓ Backend Setup:"
echo "  [ ] .env file created with GEMINI_API_KEY"
echo "  [ ] Backend runs locally: python3 src/main.py"
echo "  [ ] Can access http://localhost:8000"
echo ""
echo "✓ Frontend Setup:"
echo "  [ ] .env.local file created with VITE_CLERK_PUBLISHABLE_KEY"
echo "  [ ] Frontend runs locally: npm run dev"
echo "  [ ] Can access http://localhost:5173"
echo "  [ ] Audio upload works"
echo ""
echo "✓ Ready to Deploy:"
echo "  [ ] All changes committed to GitHub"
echo "  [ ] Have Gemini API key ready"
echo "  [ ] Have Clerk publishable key ready"
echo "  [ ] Render account created"
echo "  [ ] Vercel account created"
echo ""
echo "📚 Next Steps:"
echo "1. Read DEPLOYMENT_SUMMARY.md for quick overview"
echo "2. Follow DEPLOYMENT.md for step-by-step guide"
echo "3. Deploy backend to Render (10 min)"
echo "4. Deploy frontend to Vercel (5 min)"
echo "5. Update CORS and Clerk settings"
echo ""
echo "🚀 Let's deploy!"
