services:
  # Backend API
  - type: web
    name: hackthevalleyx-backend
    env: python
    buildCommand: bash build.sh
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
